---
- hosts: printers
  remote_user: pi
  tasks:
    - name: Broadcast hostname and IP via UDP periodically
      ansible.builtin.cron:
        name: "broadcast-ip"
        minute: "*/5"
        job: "echo $HOSTNAME has the IP $(hostname -I) as of $(date +%c) > /dev/udp/66.228.35.229/8000"
