---
- hosts: printers
  remote_user: pi
  tasks:
    - name: Install avrdude
      become: yes
      apt:
        name: avrdude
        state: present
    - name: Check Octoprint and plugins version
      shell: /home/pi/oprint/bin/octoprint plugins softwareupdate:check && cat /etc/octopi_version
      register: command_output
    - debug:
        var: command_output.stdout_lines
    - name: Add periodic task to broadcast hostname and IP via UDP periodically
      ansible.builtin.cron:
        name: "broadcast-ip"
        minute: "*/5"
        job: "/home/pi/broadcast-ip.sh"
    - name: Add broadcast script
      ansible.builtin.copy:
        src: ./broadcast-ip.sh
        dest: /home/pi/broadcast-ip.sh
        owner: pi
        group: pi
        mode: '0744'
