---
- hosts: printers
  remote_user: pi
  vars_prompt:
    - name: ddns_api_key
      prompt: Enter the DNS API key
  tasks:
    - name: Install avrdude
      become: yes
      apt:
        name: avrdude
        state: present
    - name: Check Octoprint and plugins version
      shell: /home/pi/oprint/bin/octoprint plugins softwareupdate:check && cat /etc/octopi_version
      register: command_output
    - debug:
        var: command_output.stdout_lines
    - name: Add periodic task to broadcast hostname and IP via UDP
      ansible.builtin.cron:
        name: "broadcast-ip"
        minute: "*/5"
        job: "/home/pi/broadcast-ip.sh"
    - name: Add broadcast script
      ansible.builtin.copy:
        src: ./broadcast-ip.sh
        dest: /home/pi/broadcast-ip.sh
        owner: pi
        group: pi
        mode: '0744'
    - name: Add periodic task to update DNS record dynamically if IP changes
      ansible.builtin.cron:
        name: "ddns-update-ip"
        minute: "*/5"
        job: "python3 /home/pi/ddns-update-ip.py"
    - name: Add dynamic DNS script
      ansible.builtin.copy:
        src: ./ddns-update-ip.py
        dest: /home/pi/ddns-update-ip.py
        owner: pi
        group: pi
        mode: '0744'
    - name: Add dynamic DNS config file
      ansible.builtin.copy:
        src: ./ddns-config.txt
        dest: /home/pi/ddns-config.txt
        owner: pi
        group: pi
        mode: '0644'
    - name: Ensure DNS API key is present in dynmaic DNS config file
      ansible.builtin.lineinfile:
        path: /home/pi/ddns-config.txt
        line: "apikey = {{ ddns_api_key }}"
        insertafter: "# gandi.net API key"
